image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

build_script:
  - ver

test_script:
  - cmd /c call datetime\cdate.test.bat
  - cmd /c call .\link.bat
  - cmd /c .\out.exe& exit 0
